name: scanbot_sdk_example_flutter
description: "An example app to show the integration of the Scanbot SDK Flutter Plugin."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  scanbot_sdk:
    path: ../scanbot-sdk-flutter/bundle_sdk
  image_picker: ^1.2.3
  cupertino_icons: ^2.0.0
  url_launcher: ^6.3.3
  permission_handler: ^12.0.3
  logging: ^1.3.0
  path_provider: ^2.1.6
  share_plus: ^13.3.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
