import 'package:scanbot_sdk/scanbot_sdk.dart';

Future<void> createDocument() async {
  /** Create a document with a UUID */
  var document = await ScanbotSdk.document.createDocumentFromImageFileUris();
}

Future<void> createDocumentWithPages(List<String> imageFileUris) async {
  /**
   * Create a document with a UUID
   * Add images from `imageFileUris` as document pages
   * */
  var document = await ScanbotSdk.document.createDocumentFromImageFileUris(images: imageFileUris);
}

Future<void> loadDocument(String documentID) async {
  /** Load a document from storage by ID */
  var document = await ScanbotSdk.document.loadDocument(documentID);
}

Future<void> storedDocumentUUIDs() async {
  /** Retrieve all the document IDs from the storage */
  var documentIds = await ScanbotSdk.document.getStoredDocumentIDs();
}

Future<void> reorderDocumentPages(String documentID) async {
  /** Load a document from storage by ID */
  var document = await ScanbotSdk.document.loadDocument(documentID);
  /** Move the first page to the end of the document */
  var documentWithReorderedPages = await ScanbotSdk.document.movePage(document.uuid, 0, document.pages.length - 1);
}

Future<void> removeAllPagesFromDocument(String documentID) async {
  /** Remove all the pages from a document */
  var documentWithRemovedPages = await ScanbotSdk.document.removeAllPages(documentID);
}

Future<void> deleteDocument(String documentID) async {
  /** Delete a document from storage along with the document's PDF and TIFF files */
  await ScanbotSdk.document.deleteDocument(documentID);
}

Future<void> deleteAllDocuments() async {
  /** Delete all documents from storage along with the documents' PDF and TIFF files */
  await ScanbotSdk.document.deleteAllDocuments();
}

Future<void> cleanup() async {
  /** Removes all the files generated by the Scanbot SDK including the documents */
  await ScanbotSdk.cleanupStorage();
}
